# **Data Cleaning and Preparation:** Full Digital
**Project:** Adopción Digital - Portafolio

## Import Libraries and Data Load

Se importa la libreria pandas para el manejo de datos y se cargan los datos originales CSV.

In [1]:
import pandas as pd

full_digital_df = pd.read_csv(r"../Data_raw_anon/data_full_digital.csv")

Se imprimen los primeros 5 registros del dataset

In [2]:
full_digital_df.head()

,Región,División,Distrito,CEDIS,Ruta SAP,Cliente ID,Nombre Cliente,Categoría,% Venta Digital,Venta Digital
0,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000018,Abarrotes El Progreso 72,Non Digital,0 %,$0
1,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000324,Minisuper La Esperanza 85,Non Digital,0 %,$0
2,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000612,Depósito La Fortuna 88,Non Digital,0 %,$0
3,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000613,Depósito La Victoria 37,Non Digital,0 %,$0
4,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000616,Mercadito Santa Cruz 42,Non Digital,0 %,$0

## Metadata Info

Con el método **`info()`** se obtienen los metadatos del dataset como el tipo de dato.

In [3]:
full_digital_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1789 entries, 0 to 1788
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Región           1789 non-null   str
 1   División         1789 non-null   str
 2   Distrito         1789 non-null   int64
 3   CEDIS            1789 non-null   str
 4   Ruta SAP         1789 non-null   str
 5   Cliente ID       1789 non-null   int64
 6   Nombre Cliente   1789 non-null   str
 7   Categoría        1789 non-null   str
 8   % Venta Digital  1789 non-null   str
 9   Venta Digital    1789 non-null   str
dtypes: int64(2), str(8)
memory usage: 139.9 KB

Se imprime la dimensión del dataset (registros, campos)

In [4]:
full_digital_df.shape

(1789, 10)

## Null Value Verification

Se verifica que no hayan valores nulos en los campos.

In [5]:
full_digital_df.isnull().sum()

Región             0
División           0
Distrito           0
CEDIS              0
Ruta SAP           0
Cliente ID         0
Nombre Cliente     0
Categoría          0
% Venta Digital    0
Venta Digital      0
dtype: int64

## Duplicated Value Verification

Se verifica que no hayan registros duplicados.

In [6]:
full_digital_df.duplicated().sum()

np.int64(0)

## ID´s Validation

Se verifica que los ID´s sean válidos y consistentes.

In [7]:
print("\nID ruta minimo")
print(full_digital_df['Ruta SAP'].min())

# ------------------------------------------------

print("\nID cliente minimo")
print(full_digital_df['Cliente ID'].min())

ID ruta minimo
RT001

ID cliente minimo
200000005

## Names Data Cleaning

Se estandarizan los nombres de clientes para consistencia

In [8]:
full_digital_df['Nombre Cliente'] = full_digital_df['Nombre Cliente'].str.strip()   # Quitar espacios
full_digital_df['Nombre Cliente'] = full_digital_df['Nombre Cliente'].str.title()   # Estandarizar mayúsculas
print("\nPrimeros 5 nombres normalizados:")
print(full_digital_df['Nombre Cliente'].head())

Primeros 5 nombres normalizados:
0     Abarrotes El Progreso 72
1    Minisuper La Esperanza 85
2       Depósito La Fortuna 88
3      Depósito La Victoria 37
4      Mercadito Santa Cruz 42
Name: Nombre Cliente, dtype: str

## Status Data Cleaning

Se estandarizó la columna 'Categoría ' y se verificó que solo contenga 'non digital', 'hibrido' o 'fully'.

In [9]:
full_digital_df['Categoría'] = full_digital_df['Categoría'].str.lower().str.strip()
print("\nValores únicos en Status Registro:")
print(full_digital_df['Categoría'].unique())

Valores únicos en Status Registro:
<StringArray>
['non digital', 'hibrido', 'fully']
Length: 3, dtype: str

## Standardization of Column Headers

Se estandariza el nombre de los encabezados de los campos

In [10]:
full_digital_df.columns = (
    full_digital_df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

full_digital_df.head()

,región,división,distrito,cedis,ruta_sap,cliente_id,nombre_cliente,categoría,%_venta_digital,venta_digital
0,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000018,Abarrotes El Progreso 72,non digital,0 %,$0
1,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000324,Minisuper La Esperanza 85,non digital,0 %,$0
2,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000612,Depósito La Fortuna 88,non digital,0 %,$0
3,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000613,Depósito La Victoria 37,non digital,0 %,$0
4,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000616,Mercadito Santa Cruz 42,non digital,0 %,$0

## Dataset clean and ready to export

Dataset exportado a CSV para uso en análisis y joins futuros.

In [11]:
print("\nDataset limpio y listo para análisis")
full_digital_df.to_csv(r"../Data_processed_anon/Fully_digital_clean.csv", index=False)

Dataset limpio y listo para análisis