# **Data Cleaning and Preparation:** Clients Status
**Project:** Adopción Digital - Portafolio

## Import Libraries and Data Load

Se importa la libreria pandas para el manejo de datos y se cargan los datos originales CSV.

In [1]:
import pandas as pd

registros_clientes_df = pd.read_csv(r"../Data_raw_anon/data_registros_clientes_historico.csv")

Se imprimen los primeros 5 registros del dataset.

In [2]:
registros_clientes_df.head()

   Distrito SAP   Ruta  NIP Cliente           Nombre Cliente Status Registro
0          4210  RT020    200001743     Super Buena Vista 31   No Registrado
1          4210  RT004    200001258  Comercial El Encanto 69   No Registrado
2          4210  RT008    200001737       Frutería El Sol 16   No Registrado
3          4210  RT015    200000179   Abarrotes Del Norte 98   No Registrado
4          4210  RT002    200001649   Abarrotes Del Valle 45      Registrado

## Metadata Info

Con el método **`info()`** se obtienen los metadatos del dataset como el tipo de dato.

In [3]:
registros_clientes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2114 entries, 0 to 2113
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Distrito SAP     2114 non-null   int64
 1   Ruta             2114 non-null   str
 2   NIP Cliente      2114 non-null   int64
 3   Nombre Cliente   2114 non-null   str
 4   Status Registro  2114 non-null   str
dtypes: int64(2), str(3)
memory usage: 82.7 KB

Se imprime la dimensión del dataset (registros, campos).

In [4]:
registros_clientes_df.shape

(2114, 5)

## Null Value Verification

Se verifica que no hayan valores nulos en los campos.

In [5]:
registros_clientes_df.isnull().sum()

Distrito SAP       0
Ruta               0
NIP Cliente        0
Nombre Cliente     0
Status Registro    0
dtype: int64

## Duplicated Value Verification

Se verifica que no hayan registros duplicados.

In [6]:
registros_clientes_df.duplicated().sum()

np.int64(0)

## ID´s Validation

Se verifica que los ID´s sean válidos y consistentes.

In [7]:
print("\nID ruta minimo")
print(registros_clientes_df['Ruta'].min())

# ------------------------------------------------

print("\nID cliente minimo")
print(registros_clientes_df['NIP Cliente'].min())

ID ruta minimo
RT001

ID cliente minimo
200000000

## Names Data Cleaning

Se estandarizan los nombres de clientes para consistencia

In [8]:
registros_clientes_df['Nombre Cliente'] = registros_clientes_df['Nombre Cliente'].str.strip()   # Quitar espacios
registros_clientes_df['Nombre Cliente'] = registros_clientes_df['Nombre Cliente'].str.title()   # Estandarizar mayúsculas
print("\nPrimeros 5 nombres normalizados:")
print(registros_clientes_df['Nombre Cliente'].head())

Primeros 5 nombres normalizados:
0       Super Buena Vista 31
1    Comercial El Encanto 69
2         Frutería El Sol 16
3     Abarrotes Del Norte 98
4     Abarrotes Del Valle 45
Name: Nombre Cliente, dtype: str

## Status Data Cleaning

Se estandarizó la columna 'Categoría ' y se verificó que solo contenga 'non digital', 'hibrido' o 'fully'.

In [9]:
registros_clientes_df['Status Registro'] = registros_clientes_df['Status Registro'].str.lower().str.strip()
print("\nValores únicos en Status Registro:")
print(registros_clientes_df['Status Registro'].unique())

Valores únicos en Status Registro:
<StringArray>
['no registrado', 'registrado']
Length: 2, dtype: str

In [10]:
registros_clientes_df.head(10)

   Distrito SAP   Ruta  NIP Cliente           Nombre Cliente Status Registro
0          4210  RT020    200001743     Super Buena Vista 31   no registrado
1          4210  RT004    200001258  Comercial El Encanto 69   no registrado
2          4210  RT008    200001737       Frutería El Sol 16   no registrado
3          4210  RT015    200000179   Abarrotes Del Norte 98   no registrado
4          4210  RT002    200001649   Abarrotes Del Valle 45      registrado
5          4210  RT009    200001555  Minisuper El Mirador 31      registrado
6          4210  RT022    200000915     Tienda La Victoria 5      registrado
7          4210  RT007    200000912      Super Santa Cruz 48   no registrado
8          4210  RT018    200001346     Frutería San José 88   no registrado
9          4210  RT017    200001012  Minisuper La Fortuna 89      registrado

## Standardization of Column Headers

Se estandariza el nombre de los encabezados de los campos

In [11]:
registros_clientes_df.columns = (
    registros_clientes_df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

registros_clientes_df.head()

   distrito_sap   ruta  nip_cliente           nombre_cliente status_registro
0          4210  RT020    200001743     Super Buena Vista 31   no registrado
1          4210  RT004    200001258  Comercial El Encanto 69   no registrado
2          4210  RT008    200001737       Frutería El Sol 16   no registrado
3          4210  RT015    200000179   Abarrotes Del Norte 98   no registrado
4          4210  RT002    200001649   Abarrotes Del Valle 45      registrado

## Dataset clean and ready to export

Dataset exportado a CSV para uso en análisis y joins futuros.

In [12]:
print("\nDataset limpio y listo para análisis")
registros_clientes_df.to_csv(r"../Data_processed_anon/Registros_Clientes_clean.csv", index=False)

Dataset limpio y listo para análisis