# **Data Transform**: Full Digital

**Project:** Adopción Digital - Portafolio

*En esta notebook se documentó el proceso de transformación y anonimación de datos cuidando la confidencialidad de la empresa.*

## Import Libraries and Data Load

Se importa la libreria pandas para el manejo de datos y se cargan los datos procesados CSV.

In [1]:
import pandas as pd

status_df = pd.read_csv(r"../Data_processed_anon/Fully_digital_clean.csv")
registros_df= pd.read_csv(r"../Data_processed_anon/Registros_Clientes_clean.csv")

Se imprimen los nombres de los campos en ambas tablas.

In [2]:
status_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1789 entries, 0 to 1788
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   región           1789 non-null   str
 1   división         1789 non-null   str
 2   distrito         1789 non-null   int64
 3   cedis            1789 non-null   str
 4   ruta_sap         1789 non-null   str
 5   cliente_id       1789 non-null   int64
 6   nombre_cliente   1789 non-null   str
 7   categoría        1789 non-null   str
 8   %_venta_digital  1789 non-null   str
 9   venta_digital    1789 non-null   str
dtypes: int64(2), str(8)
memory usage: 139.9 KB

In [3]:
registros_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2114 entries, 0 to 2113
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   distrito_sap     2114 non-null   int64
 1   ruta             2114 non-null   str
 2   nip_cliente      2114 non-null   int64
 3   nombre_cliente   2114 non-null   str
 4   status_registro  2114 non-null   str
dtypes: int64(2), str(3)
memory usage: 82.7 KB

## Client ID Mapping

Se crea un mapeo para el campo Cliente ID.

In [4]:
#Se construye el universo de clientes

all_clients = pd.concat([
    registros_df['nip_cliente'],
    status_df['cliente_id']
]).unique()

In [5]:
#Se construye el mapa
client_map = {
    original_id: f"CUST_{str(i+1).zfill(4)}"
    for i, original_id in enumerate(all_clients)
}

In [6]:
#Se mapea 
registros_df['cliente_anon_id'] = registros_df['nip_cliente'].map(client_map)
status_df['cliente_anon_id']    = status_df['cliente_id'].map(client_map)

In [7]:
status_df.head()

,región,división,distrito,cedis,ruta_sap,cliente_id,nombre_cliente,categoría,%_venta_digital,venta_digital,cliente_anon_id
0,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000018,Abarrotes El Progreso 72,non digital,0 %,$0,CUST_1470
1,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000324,Minisuper La Esperanza 85,non digital,0 %,$0,CUST_1456
2,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000612,Depósito La Fortuna 88,non digital,0 %,$0,CUST_1929
3,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000613,Depósito La Victoria 37,non digital,0 %,$0,CUST_1475
4,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000616,Mercadito Santa Cruz 42,non digital,0 %,$0,CUST_2023

In [8]:
registros_df.head()

,distrito_sap,ruta,nip_cliente,nombre_cliente,status_registro,cliente_anon_id
0,4210,RT020,200001743,Super Buena Vista 31,no registrado,CUST_0001
1,4210,RT004,200001258,Comercial El Encanto 69,no registrado,CUST_0002
2,4210,RT008,200001737,Frutería El Sol 16,no registrado,CUST_0003
3,4210,RT015,200000179,Abarrotes Del Norte 98,no registrado,CUST_0004
4,4210,RT002,200001649,Abarrotes Del Valle 45,registrado,CUST_0005

In [9]:
registros_df[registros_df['nombre_cliente']=='Tienda Ejemplo']

Empty DataFrame
Columns: [distrito_sap, ruta, nip_cliente, nombre_cliente, status_registro, cliente_anon_id]
Index: []

In [10]:
registros_df.isnull().sum()

distrito_sap       0
ruta               0
nip_cliente        0
nombre_cliente     0
status_registro    0
cliente_anon_id    0
dtype: int64

In [11]:
status_df.isnull().sum()

región             0
división           0
distrito           0
cedis              0
ruta_sap           0
cliente_id         0
nombre_cliente     0
categoría          0
%_venta_digital    0
venta_digital      0
cliente_anon_id    0
dtype: int64

## Route ID Mapping

Se crea un mapeo para el campo Ruta ID.

In [12]:
#Se construye el universo de rutas

all_routes = pd.concat([
    registros_df['ruta'],
    status_df['ruta_sap']
]).unique()

In [13]:
#Se construye el mapa
route_map = {
    original_id: f"ROUTE_{str(i+1).zfill(4)}"
    for i, original_id in enumerate(all_routes)
}

In [14]:
registros_df["ruta_anon"] = registros_df["ruta"].map(route_map)
status_df["ruta_anon"] = status_df["ruta_sap"].map(route_map)

In [15]:
registros_df.head()

,distrito_sap,ruta,nip_cliente,nombre_cliente,status_registro,cliente_anon_id,ruta_anon
0,4210,RT020,200001743,Super Buena Vista 31,no registrado,CUST_0001,ROUTE_0001
1,4210,RT004,200001258,Comercial El Encanto 69,no registrado,CUST_0002,ROUTE_0002
2,4210,RT008,200001737,Frutería El Sol 16,no registrado,CUST_0003,ROUTE_0003
3,4210,RT015,200000179,Abarrotes Del Norte 98,no registrado,CUST_0004,ROUTE_0004
4,4210,RT002,200001649,Abarrotes Del Valle 45,registrado,CUST_0005,ROUTE_0005

In [16]:
status_df.head()

,región,división,distrito,cedis,ruta_sap,cliente_id,nombre_cliente,categoría,%_venta_digital,venta_digital,cliente_anon_id,ruta_anon
0,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000018,Abarrotes El Progreso 72,non digital,0 %,$0,CUST_1470,ROUTE_0020
1,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000324,Minisuper La Esperanza 85,non digital,0 %,$0,CUST_1456,ROUTE_0020
2,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000612,Depósito La Fortuna 88,non digital,0 %,$0,CUST_1929,ROUTE_0020
3,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000613,Depósito La Victoria 37,non digital,0 %,$0,CUST_1475,ROUTE_0020
4,NORESTE,DIV MONTERREY,4210,150 SAN NICOLAS DE LOS GARZA,RT001,200000616,Mercadito Santa Cruz 42,non digital,0 %,$0,CUST_2023,ROUTE_0020

In [17]:
registros_df.isnull().sum()

distrito_sap       0
ruta               0
nip_cliente        0
nombre_cliente     0
status_registro    0
cliente_anon_id    0
ruta_anon          0
dtype: int64

In [18]:
status_df.isnull().sum()

región             0
división           0
distrito           0
cedis              0
ruta_sap           0
cliente_id         0
nombre_cliente     0
categoría          0
%_venta_digital    0
venta_digital      0
cliente_anon_id    0
ruta_anon          0
dtype: int64

In [19]:
registros_df[registros_df['nombre_cliente']=='Tienda Ejemplo']

Empty DataFrame
Columns: [distrito_sap, ruta, nip_cliente, nombre_cliente, status_registro, cliente_anon_id, ruta_anon]
Index: []

## Name Anonymized

Se anonimizarón los nombre para proteger la confidencialidad e información sensible.

In [20]:
registros_df[['cliente_anon_id', 'nombre_cliente']].head()

  cliente_anon_id           nombre_cliente
0       CUST_0001     Super Buena Vista 31
1       CUST_0002  Comercial El Encanto 69
2       CUST_0003       Frutería El Sol 16
3       CUST_0004   Abarrotes Del Norte 98
4       CUST_0005   Abarrotes Del Valle 45

In [21]:
unique_clients = registros_df['cliente_anon_id'].dropna().unique()

name_map = {
    client: f"Store_{str(i+1).zfill(4)}"
    for i, client in enumerate(unique_clients)
}

In [22]:
status_df['nombre_anon'] = status_df['cliente_anon_id'].map(name_map)
registros_df['nombre_anon'] = registros_df['cliente_anon_id'].map(name_map)

In [23]:
registros_df[['cliente_anon_id', 'nombre_anon']].head()

  cliente_anon_id nombre_anon
0       CUST_0001  Store_0001
1       CUST_0002  Store_0002
2       CUST_0003  Store_0003
3       CUST_0004  Store_0004
4       CUST_0005  Store_0005

In [24]:
status_df[['cliente_anon_id', 'nombre_anon']].head()

  cliente_anon_id nombre_anon
0       CUST_1470  Store_1470
1       CUST_1456  Store_1456
2       CUST_1929  Store_1929
3       CUST_1475  Store_1475
4       CUST_2023  Store_2023

In [25]:
registros_df[registros_df['nombre_cliente']=='Tienda Ejemplo']

Empty DataFrame
Columns: [distrito_sap, ruta, nip_cliente, nombre_cliente, status_registro, cliente_anon_id, ruta_anon, nombre_anon]
Index: []

## Fields Dropped

Se eliminarán los campos que contengan información sensible para proteger la confidencialidad e integridad de los datos.

In [26]:
registros_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2114 entries, 0 to 2113
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   distrito_sap     2114 non-null   int64
 1   ruta             2114 non-null   str
 2   nip_cliente      2114 non-null   int64
 3   nombre_cliente   2114 non-null   str
 4   status_registro  2114 non-null   str
 5   cliente_anon_id  2114 non-null   str
 6   ruta_anon        2114 non-null   str
 7   nombre_anon      2114 non-null   str
dtypes: int64(2), str(6)
memory usage: 132.3 KB

In [27]:
status_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1789 entries, 0 to 1788
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   región           1789 non-null   str
 1   división         1789 non-null   str
 2   distrito         1789 non-null   int64
 3   cedis            1789 non-null   str
 4   ruta_sap         1789 non-null   str
 5   cliente_id       1789 non-null   int64
 6   nombre_cliente   1789 non-null   str
 7   categoría        1789 non-null   str
 8   %_venta_digital  1789 non-null   str
 9   venta_digital    1789 non-null   str
 10  cliente_anon_id  1789 non-null   str
 11  ruta_anon        1789 non-null   str
 12  nombre_anon      1788 non-null   str
dtypes: int64(2), str(11)
memory usage: 181.8 KB

In [28]:
registros_df = registros_df.drop(columns=["distrito_sap", "nip_cliente", "nombre_cliente", "ruta"])

new_order = [
    "ruta_anon",
    "cliente_anon_id",
    "nombre_anon",
    "status_registro",
   
]

registros_df = registros_df[new_order]
registros_df.head()

    ruta_anon cliente_anon_id nombre_anon status_registro
0  ROUTE_0001       CUST_0001  Store_0001   no registrado
1  ROUTE_0002       CUST_0002  Store_0002   no registrado
2  ROUTE_0003       CUST_0003  Store_0003   no registrado
3  ROUTE_0004       CUST_0004  Store_0004   no registrado
4  ROUTE_0005       CUST_0005  Store_0005      registrado

In [29]:
status_df = status_df.drop(columns=["región", "división", "distrito", "cedis", "ruta_sap", "cliente_id", "nombre_cliente", "venta_digital"])

new_order = [
    "ruta_anon",
    "cliente_anon_id",
    "nombre_anon",
    "categoría",
    "%_venta_digital",
   
]

status_df = status_df[new_order]
status_df.head()

    ruta_anon cliente_anon_id nombre_anon    categoría %_venta_digital
0  ROUTE_0020       CUST_1470  Store_1470  non digital             0 %
1  ROUTE_0020       CUST_1456  Store_1456  non digital             0 %
2  ROUTE_0020       CUST_1929  Store_1929  non digital             0 %
3  ROUTE_0020       CUST_1475  Store_1475  non digital             0 %
4  ROUTE_0020       CUST_2023  Store_2023  non digital             0 %

## Dataset clean and ready to export

Datasets limpio, anonimizado y exportado a CSV para uso en análisis y joins futuros.

In [30]:
print("\nDatasets limpios y listo para análisis")
status_df.to_csv("../Data_processed_anon/Status_Client_v2.csv", index=False)
registros_df.to_csv("../Data_processed_anon/Registered_Client_v2.csv", index=False)

Datasets limpios y listo para análisis